### ISSUE TITLE
ESP doesn't work at all

### ISSUE THREAD

**Issue by eshockerman** [Ennui-Ninja/Simple-AIO-Gatherer#4]
ESP doesn't work and simple gatherer doesn't find .3 anything it seems like

**Comment by clrlslwi** [comment]
Apologies. We're working on a fix. I'll post an issue tracker link here once I have it.

**Comment by eshockerman** [comment]
Thanks!

**Comment by clrlslwi** [comment]
We've fixed the problem. Please request compensation in tickets if we've inconvenienced you.

Thank you.
